output_dir: output
dtype: fp16
device: cuda
mixed_precision: fp16
model:
  num_step: 50
  base_model: "./resource/diffuser/sd15"
  controlnet: "./resource/diffuser/controlnet_depth"
mesh:
  path: "dataset/future/Desk"
  shape_scale: 1
  dy: 0
  render_size: 384
  texture_resolution: 512
  texture_interpolation_mode: "bilinear"
  texture_unet_path: "output/unet_l.pth"
