output_dir: output
dtype: fp16
device: cuda
mixed_precision: fp16
dataset:
  path: "./dataset/512_new"
model:
  num_step: 50
  type: "sdxl"
  base_model: "./resource/sdxl_base"
  controlnet: "./resource/sdxl_controlnet"
  image_encoder: "./resource/clip14" 
masa:
  ref_idx: 22
  tar_idx: 5
  size: 1024
mesh:
  path: "resource/3D_Future"
  shape_scale: 1
  dy: 0
  texture_resolution: 512
  texture_interpolation_mode: "bilinear"
