dtype: fp16
device: cuda
mixed_precision: fp16
dataset:
  path: "./dataset/512_new"
model:
  num_step: 50
  base_model: "./resource/sd15"
  controlnet: "./resource/controlnet_depth"
  image_encoder: "./resource/clip14" 
mesh:
  path: "resource/3D_Future"
  shape_scale: 1
  dy: 0
  render_size: 192
  texture_resolution: 256
  texture_interpolation_mode: "bilinear"
